
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.18.0
 * Query Engine version: 34b5a692b7bd79939a9a2c3ef97d816e749cda2f
 */
Prisma.prismaVersion = {
  client: "6.18.0",
  engine: "34b5a692b7bd79939a9a2c3ef97d816e749cda2f"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.ContestScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  banner: 'banner',
  status: 'status',
  isMoneyContest: 'isMoneyContest',
  maxPrize: 'maxPrize',
  minPrize: 'minPrize',
  startDate: 'startDate',
  endDate: 'endDate',
  startedAt: 'startedAt',
  endedAt: 'endedAt',
  finalizedAt: 'finalizedAt',
  recurringContestId: 'recurringContestId',
  configVersion: 'configVersion',
  scoringVersion: 'scoringVersion',
  creatorId: 'creatorId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RecurringContestScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  banner: 'banner',
  isMoneyContest: 'isMoneyContest',
  maxPrize: 'maxPrize',
  minPrize: 'minPrize',
  startDate: 'startDate',
  endDate: 'endDate',
  creatorId: 'creatorId',
  status: 'status',
  lastGeneratedContestId: 'lastGeneratedContestId',
  rules: 'rules',
  prizes: 'prizes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RecurringContestOccurrenceScalarFieldEnum = {
  id: 'id',
  occurrenceKey: 'occurrenceKey',
  recurringContestId: 'recurringContestId',
  scheduledAt: 'scheduledAt',
  contestId: 'contestId',
  status: 'status',
  startedAt: 'startedAt',
  error: 'error',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PrizeScalarFieldEnum = {
  id: 'id',
  category: 'category',
  type: 'type',
  target: 'target',
  rankLimit: 'rankLimit',
  title: 'title',
  description: 'description',
  icon: 'icon',
  boost: 'boost',
  swap: 'swap',
  key: 'key',
  coin: 'coin',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ContestRuleScalarFieldEnum = {
  id: 'id',
  icon: 'icon',
  name: 'name',
  description: 'description',
  contestId: 'contestId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ContestRuleConfigScalarFieldEnum = {
  id: 'id',
  contestId: 'contestId',
  key: 'key',
  value: 'value',
  enabled: 'enabled',
  order: 'order',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ContestPhotoScalarFieldEnum = {
  id: 'id',
  title: 'title',
  contestId: 'contestId',
  participantId: 'participantId',
  photoId: 'photoId',
  rank: 'rank',
  promoted: 'promoted',
  promotionExpiresAt: 'promotionExpiresAt',
  initialVotes: 'initialVotes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ContestParticipantScalarFieldEnum = {
  id: 'id',
  status: 'status',
  contestId: 'contestId',
  userId: 'userId',
  memberId: 'memberId',
  level: 'level',
  rank: 'rank',
  exposure_bonus: 'exposure_bonus',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ContestPrizeScalarFieldEnum = {
  id: 'id',
  category: 'category',
  type: 'type',
  target: 'target',
  rankLimit: 'rankLimit',
  icon: 'icon',
  boost: 'boost',
  swap: 'swap',
  key: 'key',
  coin: 'coin',
  contestId: 'contestId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ContestRuleAcceptanceScalarFieldEnum = {
  id: 'id',
  contestId: 'contestId',
  userId: 'userId',
  key: 'key',
  acceptedAt: 'acceptedAt',
  ruleVersion: 'ruleVersion'
};

exports.Prisma.ContestAwardScalarFieldEnum = {
  id: 'id',
  category: 'category',
  type: 'type',
  target: 'target',
  rankLimit: 'rankLimit',
  slotKey: 'slotKey',
  title: 'title',
  description: 'description',
  icon: 'icon',
  boost: 'boost',
  swap: 'swap',
  key: 'key',
  coin: 'coin',
  contestId: 'contestId',
  prizeId: 'prizeId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RecurringContestAwardScalarFieldEnum = {
  id: 'id',
  category: 'category',
  type: 'type',
  target: 'target',
  rankLimit: 'rankLimit',
  slotKey: 'slotKey',
  title: 'title',
  description: 'description',
  icon: 'icon',
  boost: 'boost',
  swap: 'swap',
  key: 'key',
  coin: 'coin',
  recurringContestId: 'recurringContestId',
  prizeId: 'prizeId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ContestAchievementScalarFieldEnum = {
  id: 'id',
  category: 'category',
  kind: 'kind',
  type: 'type',
  target: 'target',
  rankLimit: 'rankLimit',
  levelBadge: 'levelBadge',
  levelOrder: 'levelOrder',
  photoId: 'photoId',
  participantId: 'participantId',
  contestId: 'contestId',
  grantKey: 'grantKey',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ContestFinalizationScalarFieldEnum = {
  id: 'id',
  contestId: 'contestId',
  status: 'status',
  attemptCount: 'attemptCount',
  scoringVersion: 'scoringVersion',
  startedAt: 'startedAt',
  completedAt: 'completedAt',
  error: 'error',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ContestRankingResultScalarFieldEnum = {
  id: 'id',
  resultKey: 'resultKey',
  contestId: 'contestId',
  scope: 'scope',
  participantId: 'participantId',
  photoId: 'photoId',
  score: 'score',
  rank: 'rank',
  level: 'level',
  tieBreakKey: 'tieBreakKey',
  scoringVersion: 'scoringVersion',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ContestAwardGrantScalarFieldEnum = {
  id: 'id',
  grantKey: 'grantKey',
  contestId: 'contestId',
  contestAwardId: 'contestAwardId',
  participantId: 'participantId',
  userId: 'userId',
  photoId: 'photoId',
  category: 'category',
  kind: 'kind',
  type: 'type',
  target: 'target',
  rankLimit: 'rankLimit',
  levelBadge: 'levelBadge',
  levelOrder: 'levelOrder',
  rank: 'rank',
  keyReward: 'keyReward',
  boostReward: 'boostReward',
  swapReward: 'swapReward',
  coinReward: 'coinReward',
  status: 'status',
  error: 'error',
  processedAt: 'processedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ContestAwardSelectionScalarFieldEnum = {
  id: 'id',
  selectionKey: 'selectionKey',
  contestId: 'contestId',
  contestAwardId: 'contestAwardId',
  slotKey: 'slotKey',
  photoId: 'photoId',
  participantId: 'participantId',
  selectedById: 'selectedById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ContestRewardTransactionScalarFieldEnum = {
  id: 'id',
  grantId: 'grantId',
  userId: 'userId',
  key: 'key',
  boost: 'boost',
  swap: 'swap',
  coin: 'coin',
  createdAt: 'createdAt'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  title: 'title',
  message: 'message',
  type: 'type',
  isSent: 'isSent',
  isRead: 'isRead',
  receiverId: 'receiverId',
  data: 'data',
  createdAt: 'createdAt',
  updatedAT: 'updatedAT'
};

exports.Prisma.PaymentScalarFieldEnum = {
  id: 'id',
  status: 'status',
  productId: 'productId',
  planId: 'planId',
  subscriptionId: 'subscriptionId',
  planName: 'planName',
  recurring: 'recurring',
  userId: 'userId',
  stripe_sessino_id: 'stripe_sessino_id',
  amount: 'amount',
  currency: 'currency',
  method: 'method',
  type: 'type',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SubscriptionPlanScalarFieldEnum = {
  id: 'id',
  planName: 'planName',
  stripe_price_id: 'stripe_price_id',
  stripe_product_id: 'stripe_product_id',
  amount: 'amount',
  recurring: 'recurring',
  currency: 'currency',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SubscriptionScalarFieldEnum = {
  id: 'id',
  plan: 'plan',
  plan_id: 'plan_id',
  userId: 'userId',
  status: 'status',
  stripe_session_id: 'stripe_session_id',
  subscription_id: 'subscription_id',
  startDate: 'startDate',
  endDate: 'endDate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SitePolicyScalarFieldEnum = {
  id: 'id',
  type: 'type',
  content: 'content',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RoomScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId'
};

exports.Prisma.ChatScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  senderId: 'senderId',
  message: 'message',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  productType: 'productType',
  title: 'title',
  quantity: 'quantity',
  amount: 'amount',
  currency: 'currency',
  icon: 'icon',
  description: 'description',
  image: 'image',
  status: 'status'
};

exports.Prisma.PriceScalarFieldEnum = {
  id: 'id',
  product_id: 'product_id',
  name: 'name',
  amount: 'amount',
  quantity: 'quantity',
  price_id: 'price_id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TeamScalarFieldEnum = {
  id: 'id',
  name: 'name',
  level: 'level',
  language: 'language',
  country: 'country',
  description: 'description',
  accessibility: 'accessibility',
  member_count: 'member_count',
  score: 'score',
  win: 'win',
  lost: 'lost',
  badge: 'badge',
  min_requirement: 'min_requirement',
  min_requirement_str: 'min_requirement_str',
  creatorId: 'creatorId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TeamMatchScalarFieldEnum = {
  id: 'id',
  contestId: 'contestId',
  team1Id: 'team1Id',
  team2Id: 'team2Id',
  status: 'status',
  startedAt: 'startedAt',
  endedAt: 'endedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TeamMemberScalarFieldEnum = {
  id: 'id',
  status: 'status',
  level: 'level',
  teamId: 'teamId',
  memberId: 'memberId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TeamParticipationScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  contestId: 'contestId'
};

exports.Prisma.TeamInvitationScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  receiverId: 'receiverId',
  senderId: 'senderId',
  status: 'status',
  expiredAt: 'expiredAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  cover: 'cover',
  avatar: 'avatar',
  socialId: 'socialId',
  socialProvider: 'socialProvider',
  firstName: 'firstName',
  lastName: 'lastName',
  fullName: 'fullName',
  username: 'username',
  phone: 'phone',
  email: 'email',
  location: 'location',
  country: 'country',
  password: 'password',
  customerId: 'customerId',
  role: 'role',
  accessToken: 'accessToken',
  isActive: 'isActive',
  currentLevel: 'currentLevel',
  voting_power: 'voting_power',
  purchased_plan: 'purchased_plan',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserStoreScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  key: 'key',
  boost: 'boost',
  swap: 'swap',
  coin: 'coin',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserPhotoScalarFieldEnum = {
  id: 'id',
  url: 'url',
  userId: 'userId',
  views: 'views',
  labels: 'labels',
  title: 'title',
  description: 'description',
  adult: 'adult',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LikeScalarFieldEnum = {
  id: 'id',
  providerId: 'providerId',
  photoId: 'photoId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OtpScalarFieldEnum = {
  id: 'id',
  code: 'code',
  expires_in: 'expires_in',
  userId: 'userId',
  otpStatus: 'otpStatus',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  expiresAt: 'expiresAt'
};

exports.Prisma.CommentScalarFieldEnum = {
  id: 'id',
  text: 'text',
  providerId: 'providerId',
  photoId: 'photoId',
  parentId: 'parentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FollowScalarFieldEnum = {
  id: 'id',
  followerId: 'followerId',
  followingId: 'followingId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VoteScalarFieldEnum = {
  id: 'id',
  providerId: 'providerId',
  photoId: 'photoId',
  contestId: 'contestId',
  type: 'type',
  power: 'power',
  weight: 'weight',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserLevelScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  levelId: 'levelId'
};

exports.Prisma.LevelScalarFieldEnum = {
  id: 'id',
  level: 'level',
  levelName: 'levelName',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};
exports.ContestStatus = exports.$Enums.ContestStatus = {
  JOINED: 'JOINED',
  OPEN: 'OPEN',
  NEW: 'NEW',
  UPCOMING: 'UPCOMING',
  ACTIVE: 'ACTIVE',
  FINALIZING: 'FINALIZING',
  FINALIZATION_FAILED: 'FINALIZATION_FAILED',
  COMPLETED: 'COMPLETED',
  CLOSED: 'CLOSED'
};

exports.RecurringContestStatus = exports.$Enums.RecurringContestStatus = {
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  ENDED: 'ENDED'
};

exports.ContestOccurrenceStatus = exports.$Enums.ContestOccurrenceStatus = {
  PENDING: 'PENDING',
  MATERIALIZING: 'MATERIALIZING',
  MATERIALIZED: 'MATERIALIZED',
  FAILED: 'FAILED'
};

exports.PrizeType = exports.$Enums.PrizeType = {
  TOP_PHOTO: 'TOP_PHOTO',
  TOP_PHOTOGRAPHER: 'TOP_PHOTOGRAPHER',
  AMATEUR: 'AMATEUR',
  TALENTED: 'TALENTED',
  SUPREME: 'SUPREME',
  SUPERIOR: 'SUPERIOR',
  YC_PICK: 'YC_PICK',
  TOP_100: 'TOP_100',
  TOP_50: 'TOP_50',
  TOP_20: 'TOP_20',
  TOP_10: 'TOP_10',
  WINNER: 'WINNER'
};

exports.AwardType = exports.$Enums.AwardType = {
  TOP_RANK: 'TOP_RANK',
  TOP_PHOTO: 'TOP_PHOTO',
  TOP_PHOTOGRAPHER: 'TOP_PHOTOGRAPHER',
  WINNER: 'WINNER',
  YC_PICK: 'YC_PICK'
};

exports.AwardTarget = exports.$Enums.AwardTarget = {
  PHOTO: 'PHOTO',
  PHOTOGRAPHER: 'PHOTOGRAPHER'
};

exports.ContestParticipantStatus = exports.$Enums.ContestParticipantStatus = {
  ACTIVE: 'ACTIVE',
  BLOCKED: 'BLOCKED'
};

exports.YCLevel = exports.$Enums.YCLevel = {
  NEW: 'NEW',
  AMATEUR: 'AMATEUR',
  TALENTED: 'TALENTED',
  SUPREME: 'SUPREME',
  SUPERIOR: 'SUPERIOR',
  TOP_NOTCH: 'TOP_NOTCH'
};

exports.AchievementKind = exports.$Enums.AchievementKind = {
  CONTEST_AWARD: 'CONTEST_AWARD',
  CONTEST_LEVEL: 'CONTEST_LEVEL'
};

exports.ContestLevelBadge = exports.$Enums.ContestLevelBadge = {
  AMATEUR: 'AMATEUR',
  TALENTED: 'TALENTED',
  SUPREME: 'SUPREME',
  SUPERIOR: 'SUPERIOR'
};

exports.ContestFinalizationStatus = exports.$Enums.ContestFinalizationStatus = {
  PENDING: 'PENDING',
  RUNNING: 'RUNNING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
};

exports.ContestRankingScope = exports.$Enums.ContestRankingScope = {
  PHOTO: 'PHOTO',
  PHOTOGRAPHER: 'PHOTOGRAPHER'
};

exports.ContestGrantStatus = exports.$Enums.ContestGrantStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
};

exports.NotificationType = exports.$Enums.NotificationType = {
  DEFAULT: 'DEFAULT',
  INVITATION: 'INVITATION',
  PAYMENT: 'PAYMENT',
  VOTE: 'VOTE',
  LIKE: 'LIKE'
};

exports.PaymentStatus = exports.$Enums.PaymentStatus = {
  PENDING: 'PENDING',
  SUCCEEDED: 'SUCCEEDED',
  VALID: 'VALID',
  EXPIRED: 'EXPIRED',
  FAILED: 'FAILED'
};

exports.SubscriptionPlanEnum = exports.$Enums.SubscriptionPlanEnum = {
  PREMIUM: 'PREMIUM',
  PRO: 'PRO',
  FREE: 'FREE'
};

exports.PlanRecurringType = exports.$Enums.PlanRecurringType = {
  ONETIME: 'ONETIME',
  MONTHLY: 'MONTHLY',
  YEARLY: 'YEARLY'
};

exports.PaymentType = exports.$Enums.PaymentType = {
  STORE: 'STORE',
  SUBSCRIPTION: 'SUBSCRIPTION',
  CONTEST: 'CONTEST'
};

exports.SubscriptionPlanStatus = exports.$Enums.SubscriptionPlanStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE'
};

exports.SubscriptionStatus = exports.$Enums.SubscriptionStatus = {
  PENDING: 'PENDING',
  VALID: 'VALID',
  EXPIRED: 'EXPIRED'
};

exports.SitePolicyType = exports.$Enums.SitePolicyType = {
  TERMS: 'TERMS',
  POLICY: 'POLICY',
  ABOUT: 'ABOUT'
};

exports.ProductType = exports.$Enums.ProductType = {
  KEY: 'KEY',
  BOOST: 'BOOST',
  SWAP: 'SWAP',
  COIN: 'COIN'
};

exports.ProductStatus = exports.$Enums.ProductStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  DISCONTINUED: 'DISCONTINUED'
};

exports.TeamAccessibility = exports.$Enums.TeamAccessibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE'
};

exports.MatchStatus = exports.$Enums.MatchStatus = {
  ACTIVE: 'ACTIVE',
  CLOSED: 'CLOSED'
};

exports.TeamMemberStatus = exports.$Enums.TeamMemberStatus = {
  ACTIVE: 'ACTIVE',
  REMOVED: 'REMOVED',
  BLOCKED: 'BLOCKED'
};

exports.MemberLevel = exports.$Enums.MemberLevel = {
  NEW: 'NEW',
  EXPERT: 'EXPERT',
  MASTER: 'MASTER',
  LEADER: 'LEADER'
};

exports.InvitationStatus = exports.$Enums.InvitationStatus = {
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED'
};

exports.UserRole = exports.$Enums.UserRole = {
  USER: 'USER',
  ADMIN: 'ADMIN'
};

exports.OtpStatus = exports.$Enums.OtpStatus = {
  CREATED: 'CREATED',
  VALIDATED: 'VALIDATED'
};

exports.VoteType = exports.$Enums.VoteType = {
  Promoted: 'Promoted',
  Organic: 'Organic'
};

exports.LevelName = exports.$Enums.LevelName = {
  APPRENTICE: 'APPRENTICE',
  STUDENT: 'STUDENT',
  TRAINED: 'TRAINED',
  TALENTED: 'TALENTED',
  CONTENDER: 'CONTENDER',
  VIRTUOSO: 'VIRTUOSO',
  LEADER: 'LEADER',
  AVANTGARDE: 'AVANTGARDE',
  PRO: 'PRO'
};

exports.RecurringType = exports.$Enums.RecurringType = {
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY'
};

exports.Prisma.ModelName = {
  Contest: 'Contest',
  RecurringContest: 'RecurringContest',
  RecurringContestOccurrence: 'RecurringContestOccurrence',
  Prize: 'Prize',
  ContestRule: 'ContestRule',
  ContestRuleConfig: 'ContestRuleConfig',
  ContestPhoto: 'ContestPhoto',
  ContestParticipant: 'ContestParticipant',
  ContestPrize: 'ContestPrize',
  ContestRuleAcceptance: 'ContestRuleAcceptance',
  ContestAward: 'ContestAward',
  RecurringContestAward: 'RecurringContestAward',
  ContestAchievement: 'ContestAchievement',
  ContestFinalization: 'ContestFinalization',
  ContestRankingResult: 'ContestRankingResult',
  ContestAwardGrant: 'ContestAwardGrant',
  ContestAwardSelection: 'ContestAwardSelection',
  ContestRewardTransaction: 'ContestRewardTransaction',
  Notification: 'Notification',
  Payment: 'Payment',
  SubscriptionPlan: 'SubscriptionPlan',
  Subscription: 'Subscription',
  SitePolicy: 'SitePolicy',
  Room: 'Room',
  Chat: 'Chat',
  Product: 'Product',
  Price: 'Price',
  Team: 'Team',
  TeamMatch: 'TeamMatch',
  TeamMember: 'TeamMember',
  TeamParticipation: 'TeamParticipation',
  TeamInvitation: 'TeamInvitation',
  User: 'User',
  UserStore: 'UserStore',
  UserPhoto: 'UserPhoto',
  Like: 'Like',
  Otp: 'Otp',
  Comment: 'Comment',
  Follow: 'Follow',
  Vote: 'Vote',
  UserLevel: 'UserLevel',
  Level: 'Level'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
